---
# handlers file for ftp_server_vsftpd

# tasks:
   - name: Restart firefald
     command: echo "this task will restart the firefald services"
     notify: "restart_ufw"

# handlers:
   - name: restart_ufw
     service:
       name: ufw
       state: restarted
     listen: restart_ufw