
     # Запрет на подключение анонимным пользователям
     # Описание модуля ansible.builtin.lineinfile: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/lineinfile_module.html
- name: We will disable anonymous login
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^anonymous_enable='
    line: anonymous_enable=NO

     # Разрешаем локальный вход пользователя
- name: To allow local user login
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^#local_enable=YES'
    line: local_enable=YES

     # Разрешаем включить загрузку файлов
- name: To enable uploading file
  ansible.builtin.lineinfile:
    path: /etc/vsftpd.conf
    regexp: '^#write_enable=YES'
    line: write_enable=YES

      # Запускаем демон vsftpd
      # Описание модуля ansible.builtin.service: https://docs.ansible.com/ansible/latest/collections/ansible/builtin/service_module.html
- name: Start vsftpd demon
  ansible.builtin.service:  
        name: vsftpd
        state: started
